services:
  web-backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  web-frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html